"""
Step 3: Physiological Signal Driver Identification
==================================================

PURPOSE:
--------
Identifies the specific embedding dimensions that most strongly differentiate
between language conditions (Spanish vs. English), serving as candidate
"physiological drivers" for linguistic respiratory baseline.

This implements the core search described in the paper: looking for dimensions
where foundation model representations capture stable, task-invariant physiological
structure rather than linguistic content or recording artifacts.

Note:  Edit this pipeline to point to other data sets to get LOSO for each etc.

PAPER REFERENCE:
----------------
Section 5: A Stability-First Auditing Framework

Specifically addresses the paper's core question: "How can we determine whether 
a representation extracted by a foundation audio model constitutes a valid 
physiological signal before it is used for screening?"

KEY SCIENTIFIC HYPOTHESES BEING TESTED:
----------------------------------------
1. THE "CLIFF" HYPOTHESIS: If a small subset of dimensions (e.g., top 10) shows 
   dramatically higher weights than the rest, this suggests the model has identified
   specific, concentrated physiological parameters rather than distributed noise.

2. THE "INTEGRATED PROCESSING" HYPOTHESIS: If physiological drivers are spread 
   across the embedding space, it proves the model integrates information from 
   the entire 2-second window (the "Hardware" - full respiratory cycle) rather 
   than focusing on specific phonemes or vowel sounds (the "Software" - linguistic 
   content).

3. THE "LINGUISTIC INVARIANCE" TEST: By training to distinguish Spanish vs. English,
   then examining which dimensions the classifier relies on, we can identify:
   - Dimensions that capture LANGUAGE-SPECIFIC artifacts (should be rejected)
   - Dimensions that capture LANGUAGE-INVARIANT physiology (candidates for retention)

METHODOLOGICAL INNOVATION:
--------------------------
This approach inverts traditional feature selection:
- Instead of: "Find features that best predict disease"
- We use: "Find features that CAN predict language → then REJECT them"
- Rationale: Any dimension that strongly signals language difference is likely
  capturing linguistic/recording confounds rather than pure physiology

RELATION TO PRIOR STEPS:
------------------------
- BUILDS ON: Step 2 (mastersweepoverlapping_STEP_2.py) which created the
  50% overlap embeddings for Spanish/English emotional speech
- PROVIDES INPUT FOR: Subsequent stability and invariance audits
- CONNECTS TO PAPER: This is the initial "signal search" that feeds into the
  full auditing protocol described in Section 5

OUTPUT INTERPRETATION:
----------------------
Two possible outcomes with distinct scientific meanings:

1. "CLIFF" PATTERN (Concentrated Drivers):
   Top 10 dimensions have weights >> remaining 502 dimensions
   → Suggests: Model has identified specific, interpretable physiological parameters
   → Paper implication: These dimensions are strong candidates for stability auditing

2. "DISTRIBUTED" PATTERN (Spread Drivers):
   Weights gradually decline without sharp drop-off
   → Suggests: Model integrates holistic window information
   → Paper implication: Physiological signal may be encoded in distributed patterns
     rather than individual dimensions

USAGE:
------
1. Ensure 50% overlap embeddings exist in: /app/data/processed/esen_ovlap_50/
   (Generated by Step 2: mastersweepoverlapping_STEP_2.py)
2. Run: python physiological_driver_search.py
3. Examine output for "cliff" vs "distributed" patterns
4. Use top dimensions as input for subsequent stability/invariance audits

AUTHORS: Jim McCormack
CREATED: Feb 2026
"""

import numpy as np
import os
from pathlib import Path
from sklearn.svm import LinearSVC

# ============================================================================
# CONFIGURATION
# ============================================================================

# Data directory containing 50% overlap embeddings from Step 2
# These are Spanish/English emotional speech embeddings
DATA_DIR = "/app/data/processed/esen_ovlap_50"

# Model hyperparameters
SVM_C = 0.1           # Regularization strength (strong regularization to find sparse signals)
SVM_DUAL = False      # Use primal formulation for n_samples > n_features

# Number of top drivers to extract
TOP_K = 10

# ============================================================================
# PHYSIOLOGICAL DRIVER EXTRACTION
# ============================================================================

def extract_signal_drivers(data_dir):
    """
    Identify embedding dimensions that most strongly differentiate Spanish vs. English.
    
    SCIENTIFIC RATIONALE:
    This function trains a linear classifier to distinguish languages, then examines
    which embedding dimensions receive the highest weights. The counter-intuitive logic:
    
    "Dimensions that are GOOD at distinguishing languages are BAD for physiology"
    
    Why? Because physiological signals should be INVARIANT to language. Therefore:
    1. High-weight dimensions → Likely capture linguistic/recording artifacts
    2. These dimensions should be EXAMINED then POTENTIALLY REJECTED in invariance audit
    
    This is the first filter in the stability-first auditing framework.
    
    Args:
        data_dir (str): Path to directory containing .npy embedding files
                       Files should be named with "_EN_" or "_ES_" indicating language
    
    Returns:
        tuple: (top_indices, all_weights)
            - top_indices: Array of indices for top K dimensions (sorted descending)
            - all_weights: Array of absolute weights for all 512 dimensions
    
    PAPER CONNECTION:
    - Implements the "label-free auditing" principle 
    - Provides input for the "representation invariance" test 
    - Tests the "integrated processing" vs "specific parameter" hypotheses
    """
    
    # Load all embedding files
    files = list(Path(data_dir).glob("*.npy"))
    
    if not files:
        raise ValueError(f"No .npy files found in {data_dir}")
    
    print(f"📁 Found {len(files)} embedding files")
    print(f"🔍 Searching for physiological signal drivers...")
    print(f"   Hypothesis: Language-invariant physiology should NOT distinguish ES vs EN")
    print()
    
    # Prepare data matrix and language labels
    X = []  # Will be [n_samples, 512]
    y = []  # Binary labels: 0=Spanish, 1=English
    
    for f in files:
        # Load embedding (512-dimensional vector)
        embedding = np.load(f).flatten()
        
        if embedding.shape[0] != 512:
            raise ValueError(f"Embedding in {f.name} has wrong dimension: {embedding.shape}")
        
        X.append(embedding)
        
        # Determine language from filename
        # Files should follow naming: {SUBJECT}_{LANGUAGE}_{SEQUENCE}.npy
        if "_EN_" in f.name:
            y.append(1)  # English
        elif "_ES_" in f.name:
            y.append(0)  # Spanish
        else:
            print(f"⚠️  Warning: Could not determine language for {f.name}")
            continue
    
    X = np.array(X)
    y = np.array(y)
    
    print(f"📊 Data shape: {X.shape[0]} samples × {X.shape[1]} dimensions")
    print(f"🏷️  Class balance: {np.sum(y==0)} Spanish, {np.sum(y==1)} English")
    print()
    
    # Train linear SVM to find discriminative dimensions
    # LinearSVC with strong regularization finds sparse, interpretable weights
    print("🧠 Training diagnostic classifier...")
    print(f"   Model: LinearSVC with C={SVM_C} (strong regularization)")
    print(f"   Goal: Identify dimensions that differentiate languages")
    print()
    
    clf = LinearSVC(dual=SVM_DUAL, C=SVM_C, random_state=42, max_iter=10000)
    clf.fit(X, y)
    
    # Extract and analyze weights
    # Absolute weights indicate feature importance (magnitude matters, not sign)
    weights = np.abs(clf.coef_[0])
    
    # Sort dimensions by importance
    sorted_indices = np.argsort(weights)[::-1]  # Descending order
    sorted_weights = weights[sorted_indices]
    
    # Get top K dimensions
    top_indices = sorted_indices[:TOP_K]
    top_weights = sorted_weights[:TOP_K]
    
    # Calculate statistical summary
    weight_mean = np.mean(weights)
    weight_std = np.std(weights)
    weight_max = np.max(weights)
    weight_min = np.min(weights)
    
    # Calculate "cliffiness" metric: ratio of top weight to median weight
    cliff_ratio = top_weights[0] / np.median(weights)
    
    print(f"📈 Weight statistics:")
    print(f"   Mean: {weight_mean:.6f}, Std: {weight_std:.6f}")
    print(f"   Range: [{weight_min:.6f}, {weight_max:.6f}]")
    print(f"   Cliff ratio (top/median): {cliff_ratio:.2f}")
    print()
    
    # Interpret cliff ratio
    if cliff_ratio > 5.0:
        print("🎯 STRONG CLIFF PATTERN DETECTED")
        print("   → Model has identified specific physiological parameters")
        print("   → Top dimensions likely encode concentrated, interpretable signals")
    elif cliff_ratio > 2.0:
        print("📊 MODERATE CLIFF PATTERN")
        print("   → Some dimensions are more important than others")
        print("   → Mixed evidence for specific parameter encoding")
    else:
        print("🌊 DISTRIBUTED PATTERN DETECTED")
        print("   → Weights are relatively evenly distributed")
        print("   → Model integrates information holistically across dimensions")
    print()
    
    # Display top dimensions
    print(f"{'='*60}")
    print(f"🚀 TOP {TOP_K} PHYSIOLOGICAL DRIVER CANDIDATES")
    print(f"{'='*60}")
    print("Rank  Dimension  Weight      Relative Importance")
    print("-" * 60)
    
    for i, (idx, w) in enumerate(zip(top_indices, top_weights)):
        rel_importance = w / weight_mean
        print(f"{i+1:2d}.   {idx:4d}      {w:.6f}    {rel_importance:.2f}x average")
    
    print(f"{'='*60}")
    print()
    
    # SCIENTIFIC INTERPRETATION GUIDANCE
    print("🔬 SCIENTIFIC INTERPRETATION:")
    print()
    print("THESE DIMENSIONS ARE LANGUAGE-DISCRIMINATIVE → POTENTIAL CONFOUNDS")
    print()
    print("Next steps in auditing framework:")
    print("1. 🔍 Examine these dimensions in stability audit (Section 8.2)")
    print("   - Are they stable within subjects across tasks?")
    print("2. 🚫 Test them in invariance audit (Section 8.3)")
    print("   - Do they remain invariant to task/language/recording changes?")
    print("3. 📉 If they fail audits: REJECT as non-physiological confounds")
    print("4. ✅ If they pass: Potential physiological signal candidates")
    print()
    print("Remember: Language discrimination ≠ Physiological validity")
    print("A dimension that distinguishes ES/EN may capture:")
    print("  - Linguistic prosody patterns (REJECT)")
    print("  - Recording environment differences (REJECT)")
    print("  - Speaker demographics correlated with language (CAUTION)")
    print("  - Truly language-invariant physiology that correlates by chance (RARE)")
    
    return top_indices, weights

# ============================================================================
# MAIN EXECUTION
# ============================================================================

def main():
    """
    Execute physiological driver search and save results for downstream audits.
    
    This function:
    1. Identifies top dimensions for language discrimination
    2. Saves results for use in subsequent auditing steps
    3. Provides interpretative guidance based on paper's framework
    """
    
    print(f"{'='*70}")
    print(f"🔍 PHYSIOLOGICAL SIGNAL DRIVER SEARCH")
    print(f"{'='*70}")
    print(f"Data source: {DATA_DIR}")
    print(f"Purpose: Identify candidate dimensions for stability/invariance audits")
    print(f"Paper reference: Sections 4, 5, 8.3")
    print(f"{'='*70}")
    print()
    
    try:
        # Extract signal drivers
        top_dims, all_weights = extract_signal_drivers(DATA_DIR)
        
        # Save results for downstream use
        output_dir = "/app/data/analysis/driver_search"
        os.makedirs(output_dir, exist_ok=True)
        
        # Save top dimensions
        np.save(os.path.join(output_dir, "top_driver_indices.npy"), top_dims)
        
        # Save all weights for visualization
        np.save(os.path.join(output_dir, "all_dimension_weights.npy"), all_weights)
        
        # Save summary report
        with open(os.path.join(output_dir, "driver_search_report.txt"), "w") as f:
            f.write("PHYSIOLOGICAL DRIVER SEARCH REPORT\n")
            f.write("=" * 50 + "\n\n")
            f.write(f"Data directory: {DATA_DIR}\n")
            f.write(f"Total dimensions analyzed: 512\n")
            f.write(f"Top {len(top_dims)} driver indices:\n")
            for i, dim in enumerate(top_dims):
                f.write(f"  {i+1}. Dimension {dim} (weight: {all_weights[dim]:.6f})\n")
        
        print(f"\n💾 Results saved to: {output_dir}/")
        print(f"   - top_driver_indices.npy: Indices of top dimensions")
        print(f"   - all_dimension_weights.npy: Complete weight vector")
        print(f"   - driver_search_report.txt: Summary report")
        print()
        
        print(f"{'='*70}")
        print(f"✅ DRIVER SEARCH COMPLETE")
        print(f"   Next step: Stability audit on identified dimensions")
        print(f"   Paper reference: Section 5 (Auditing Protocol)")
        print(f"{'='*70}")
        
    except Exception as e:
        print(f"❌ Error in driver search: {e}")
        raise

# ============================================================================
# ENTRY POINT
# ============================================================================

if __name__ == "__main__":
    main()
